## -*- coding: utf-8 -*-

#importing packages
import re
import json

#soft info
__author__ = 'ELISEI SHAROV'
__name__ = 'RPB-cipher'
__version__ = '1.3'

#russian consonants in english transliteration
letter_z = 'z'
letter_s = 's'
letter_r = 'r'
letter_v = 'v'
letter_l = 'l'
letter_k = 'k'
letter_p = 'p'
letter_e = 'e'
letter_b = 'b'
letter_f = 'f'
letter_h = 'h'
letter_g = 'g'
letter_t = 't'
letter_d = 'd'
letter_m = 'm'
letter_ts = 'ts'
letter_ch = 'ch'
letter_zh = 'zh'
letter_sh = 'sh'
letter_sch = 'sch'
soft_letter = ''
strong_letter = ''
#vowels
hiragana_letter_a = 'あ'
hiragana_letter_i = 'い'
hiragana_letter_u = 'う'
hiragana_letter_e = 'え'
hiragana_letter_o = 'お'
#standart consonants
hiragana_letter_ka = 'か'
hiragana_letter_ki = 'き'
hiragana_letter_ku = 'く'
hiragana_letter_ke = 'け'
hiragana_letter_ko = 'こ'
hiragana_letter_sa = 'さ'
hiragana_letter_si = 'し'
hiragana_letter_su = 'す'
hiragana_letter_se = 'せ'
hiragana_letter_so = 'そ'
hiragana_letter_ta = 'た'
hiragana_letter_ti = 'ち'
hiragana_letter_tu = 'つ'
hiragana_letter_te = 'て'
hiragana_letter_to = 'と'
hiragana_letter_na = 'な'
hiragana_letter_ni = 'に'
hiragana_letter_nu = 'ぬ'
hiragana_letter_ne = 'ね'
hiragana_letter_no = 'の'
hiragana_letter_ha = 'は'
hiragana_letter_hi = 'ひ'
hiragana_letter_hu = 'ふ'
hiragana_letter_he = 'へ'
hiragana_letter_ho = 'ほ'
hiragana_letter_ma = 'ま'
hiragana_letter_mi = 'み'
hiragana_letter_mu = 'む'
hiragana_letter_me = 'め'
hiragana_letter_mo = 'も'
hiragana_letter_ya = 'や'
hiragana_letter_yu = 'ゆ'
hiragana_letter_yo = 'よ'
hiragana_letter_ra = 'ら'
hiragana_letter_ri = 'り'
hiragana_letter_ru = 'る'
hiragana_letter_re = 'れ'
hiragana_letter_ro = 'ろ'
hiragana_letter_wa = 'わ'
hiragana_letter_wo = 'を'
hiragana_letter_n = 'ん'
#voiced consonants
hiragana_letter_ga = 'が'
hiragana_letter_gi = 'ぎ'
hiragana_letter_gu = 'ぐ'
hiragana_letter_ge = 'げ'
hiragana_letter_go = 'ご'
hiragana_letter_za = 'ざ'
hiragana_letter_zi = 'じ'
hiragana_letter_zu = 'ず'
hiragana_letter_ze = 'ぜ'
hiragana_letter_zo = 'ぞ'
hiragana_letter_da = 'だ'
hiragana_letter_di = 'ぢ'
hiragana_letter_du = 'づ'
hiragana_letter_de = 'で'
hiragana_letter_do = 'ど'
hiragana_letter_ba = 'ば'
hiragana_letter_bi = 'び'
hiragana_letter_bu = 'ぶ'
hiragana_letter_be = 'べ'
hiragana_letter_bo = 'ぼ'
#deaf consonants
hiragana_letter_pa = 'ぱ'
hiragana_letter_pi = 'ぴ'
hiragana_letter_pu = 'ぷ'
hiragana_letter_pe = 'ぺ'
hiragana_letter_po = 'ぽ'

#japanase words
nihongo_word_rosiajin = 'ロシア人'
nihongo_word_rosia = 'ロシア'
nihongo_word_nihonjin = '日本人'
nihongo_word_nihon = '日本'
nihongo_word_amerikajin = 'アメリカ人'
nihongo_word_amerika = 'アメリカ'
nihongo_word_chuugokujin = '中国人'
nihongo_word_chuugoku = '中国'
nihongo_word_igirisujin = 'イギリス人'
nihongo_word_igirisu = 'イギリス'
nihongo_word_kankokujin = '韓国人'
nihongo_word_kankoku = '韓国'
nihongo_word_co_go = '語'

def rpb1(word_or_sentence):
    word_or_sentence = re.sub('ка', hiragana_letter_ka, word_or_sentence)
    word_or_sentence = re.sub('ки', hiragana_letter_ki, word_or_sentence)
    word_or_sentence = re.sub('кы', hiragana_letter_ki, word_or_sentence)
    word_or_sentence = re.sub('ку', hiragana_letter_ku, word_or_sentence)
    word_or_sentence = re.sub('кю', hiragana_letter_ku, word_or_sentence)
    word_or_sentence = re.sub('ке', hiragana_letter_ke, word_or_sentence)
    word_or_sentence = re.sub('кэ', hiragana_letter_ke, word_or_sentence)
    word_or_sentence = re.sub('ко', hiragana_letter_ko, word_or_sentence)
    word_or_sentence = re.sub('са', hiragana_letter_sa, word_or_sentence)
    word_or_sentence = re.sub('си', hiragana_letter_si, word_or_sentence)
    word_or_sentence = re.sub('сы', hiragana_letter_si, word_or_sentence)
    word_or_sentence = re.sub('су', hiragana_letter_su, word_or_sentence)
    word_or_sentence = re.sub('сю', hiragana_letter_su, word_or_sentence)
    word_or_sentence = re.sub('се', hiragana_letter_se, word_or_sentence)
    word_or_sentence = re.sub('сэ', hiragana_letter_se, word_or_sentence)
    word_or_sentence = re.sub('со', hiragana_letter_so, word_or_sentence)
    word_or_sentence = re.sub('на', hiragana_letter_na, word_or_sentence)
    word_or_sentence = re.sub('ни', hiragana_letter_ni, word_or_sentence)
    word_or_sentence = re.sub('ны', hiragana_letter_ni, word_or_sentence)
    word_or_sentence = re.sub('ну', hiragana_letter_nu, word_or_sentence)
    word_or_sentence = re.sub('ню', hiragana_letter_nu, word_or_sentence)
    word_or_sentence = re.sub('не', hiragana_letter_ne, word_or_sentence)
    word_or_sentence = re.sub('нэ', hiragana_letter_ne, word_or_sentence)
    word_or_sentence = re.sub('но', hiragana_letter_no, word_or_sentence)
    word_or_sentence = re.sub('та', hiragana_letter_ta, word_or_sentence)
    word_or_sentence = re.sub('ти', hiragana_letter_ti, word_or_sentence)
    word_or_sentence = re.sub('ты', hiragana_letter_ti, word_or_sentence)
    word_or_sentence = re.sub('ту', hiragana_letter_tu, word_or_sentence)
    word_or_sentence = re.sub('тю', hiragana_letter_tu, word_or_sentence)
    word_or_sentence = re.sub('те', hiragana_letter_te, word_or_sentence)
    word_or_sentence = re.sub('тэ', hiragana_letter_te, word_or_sentence)
    word_or_sentence = re.sub('то', hiragana_letter_to, word_or_sentence)
    word_or_sentence = re.sub('ха', hiragana_letter_ha, word_or_sentence)
    word_or_sentence = re.sub('хи', hiragana_letter_hi, word_or_sentence)
    word_or_sentence = re.sub('хы', hiragana_letter_hi, word_or_sentence)
    word_or_sentence = re.sub('ху', hiragana_letter_hu, word_or_sentence)
    word_or_sentence = re.sub('хю', hiragana_letter_hu, word_or_sentence)
    word_or_sentence = re.sub('хе', hiragana_letter_he, word_or_sentence)
    word_or_sentence = re.sub('хэ', hiragana_letter_he, word_or_sentence)
    word_or_sentence = re.sub('хо', hiragana_letter_ho, word_or_sentence)
    word_or_sentence = re.sub('ма', hiragana_letter_ma, word_or_sentence)
    word_or_sentence = re.sub('ми', hiragana_letter_mi, word_or_sentence)
    word_or_sentence = re.sub('мы', hiragana_letter_mi, word_or_sentence)
    word_or_sentence = re.sub('му', hiragana_letter_mu, word_or_sentence)
    word_or_sentence = re.sub('мю', hiragana_letter_mu, word_or_sentence)
    word_or_sentence = re.sub('ме', hiragana_letter_me, word_or_sentence)
    word_or_sentence = re.sub('мэ', hiragana_letter_me, word_or_sentence)
    word_or_sentence = re.sub('мо', hiragana_letter_mo, word_or_sentence)
    word_or_sentence = re.sub('я', hiragana_letter_ya, word_or_sentence)
    word_or_sentence = re.sub('ё', hiragana_letter_yo, word_or_sentence)
    word_or_sentence = re.sub('ра', hiragana_letter_ra, word_or_sentence)
    word_or_sentence = re.sub('ри', hiragana_letter_ri, word_or_sentence)
    word_or_sentence = re.sub('ры', hiragana_letter_ri, word_or_sentence)
    word_or_sentence = re.sub('ру', hiragana_letter_ru, word_or_sentence)
    word_or_sentence = re.sub('рю', hiragana_letter_ru, word_or_sentence)
    word_or_sentence = re.sub('ре', hiragana_letter_re, word_or_sentence)
    word_or_sentence = re.sub('рэ', hiragana_letter_re, word_or_sentence)
    word_or_sentence = re.sub('ро', hiragana_letter_ro, word_or_sentence)
    word_or_sentence = re.sub('ва', hiragana_letter_wa, word_or_sentence)
    word_or_sentence = re.sub('во', hiragana_letter_wo, word_or_sentence)
    word_or_sentence = re.sub('н', hiragana_letter_n, word_or_sentence)
    word_or_sentence = re.sub('га', hiragana_letter_ga, word_or_sentence)
    word_or_sentence = re.sub('ги', hiragana_letter_gi, word_or_sentence)
    word_or_sentence = re.sub('гы', hiragana_letter_gi, word_or_sentence)
    word_or_sentence = re.sub('гу', hiragana_letter_gu, word_or_sentence)
    word_or_sentence = re.sub('гю', hiragana_letter_gu, word_or_sentence)
    word_or_sentence = re.sub('ге', hiragana_letter_ge, word_or_sentence)
    word_or_sentence = re.sub('гэ', hiragana_letter_ge, word_or_sentence)
    word_or_sentence = re.sub('го', hiragana_letter_go, word_or_sentence)
    word_or_sentence = re.sub('за', hiragana_letter_za, word_or_sentence)
    word_or_sentence = re.sub('зи', hiragana_letter_zi, word_or_sentence)
    word_or_sentence = re.sub('зы', hiragana_letter_zi, word_or_sentence)
    word_or_sentence = re.sub('зу', hiragana_letter_zu, word_or_sentence)
    word_or_sentence = re.sub('зю', hiragana_letter_zu, word_or_sentence)
    word_or_sentence = re.sub('зе', hiragana_letter_ze, word_or_sentence)
    word_or_sentence = re.sub('зэ', hiragana_letter_ze, word_or_sentence)
    word_or_sentence = re.sub('зо', hiragana_letter_zo, word_or_sentence)
    word_or_sentence = re.sub('да', hiragana_letter_da, word_or_sentence)
    word_or_sentence = re.sub('ди', hiragana_letter_di, word_or_sentence)
    word_or_sentence = re.sub('ды', hiragana_letter_di, word_or_sentence)
    word_or_sentence = re.sub('ду', hiragana_letter_du, word_or_sentence)
    word_or_sentence = re.sub('дю', hiragana_letter_du, word_or_sentence)
    word_or_sentence = re.sub('де', hiragana_letter_de, word_or_sentence)
    word_or_sentence = re.sub('дэ', hiragana_letter_de, word_or_sentence)
    word_or_sentence = re.sub('до', hiragana_letter_do, word_or_sentence)
    word_or_sentence = re.sub('па', hiragana_letter_pa, word_or_sentence)
    word_or_sentence = re.sub('пи', hiragana_letter_pi, word_or_sentence)
    word_or_sentence = re.sub('пы', hiragana_letter_pi, word_or_sentence)
    word_or_sentence = re.sub('пу', hiragana_letter_pu, word_or_sentence)
    word_or_sentence = re.sub('пю', hiragana_letter_pu, word_or_sentence)
    word_or_sentence = re.sub('пе', hiragana_letter_pe, word_or_sentence)
    word_or_sentence = re.sub('пэ', hiragana_letter_pe, word_or_sentence)
    word_or_sentence = re.sub('по', hiragana_letter_po, word_or_sentence)
    word_or_sentence = re.sub('ба', hiragana_letter_ba, word_or_sentence)
    word_or_sentence = re.sub('би', hiragana_letter_bi, word_or_sentence)
    word_or_sentence = re.sub('бы', hiragana_letter_bi, word_or_sentence)
    word_or_sentence = re.sub('бу', hiragana_letter_bu, word_or_sentence)
    word_or_sentence = re.sub('бю', hiragana_letter_bu, word_or_sentence)
    word_or_sentence = re.sub('бе', hiragana_letter_be, word_or_sentence)
    word_or_sentence = re.sub('бэ', hiragana_letter_be, word_or_sentence)
    word_or_sentence = re.sub('бо', hiragana_letter_bo, word_or_sentence)
    word_or_sentence = re.sub('а', hiragana_letter_a, word_or_sentence)
    word_or_sentence = re.sub('и', hiragana_letter_i, word_or_sentence)
    word_or_sentence = re.sub('й', hiragana_letter_i, word_or_sentence)
    word_or_sentence = re.sub('у', hiragana_letter_u, word_or_sentence)
    word_or_sentence = re.sub('е', hiragana_letter_e, word_or_sentence)
    word_or_sentence = re.sub('э', hiragana_letter_e, word_or_sentence)
    word_or_sentence = re.sub('о', hiragana_letter_o, word_or_sentence)
    word_or_sentence = re.sub('з', letter_z, word_or_sentence)
    word_or_sentence = re.sub('с', letter_s, word_or_sentence)
    word_or_sentence = re.sub('р', letter_r, word_or_sentence)
    word_or_sentence = re.sub('в', letter_v, word_or_sentence)
    word_or_sentence = re.sub('л', letter_l, word_or_sentence)
    word_or_sentence = re.sub('к', letter_k, word_or_sentence)
    word_or_sentence = re.sub('п', letter_p, word_or_sentence)
    word_or_sentence = re.sub('б', letter_b, word_or_sentence)
    word_or_sentence = re.sub('ф', letter_f, word_or_sentence)
    word_or_sentence = re.sub('х', letter_h, word_or_sentence)
    word_or_sentence = re.sub('г', letter_g, word_or_sentence)
    word_or_sentence = re.sub('т', letter_t, word_or_sentence)
    word_or_sentence = re.sub('д', letter_d, word_or_sentence)
    word_or_sentence = re.sub('м', letter_m, word_or_sentence)
    word_or_sentence = re.sub('ц', letter_ts, word_or_sentence)
    word_or_sentence = re.sub('ч', letter_ch, word_or_sentence)
    word_or_sentence = re.sub('ж', letter_zh, word_or_sentence)
    word_or_sentence = re.sub('ш', letter_sh, word_or_sentence)
    word_or_sentence = re.sub('щ', letter_sch, word_or_sentence)
    word_or_sentence = re.sub('ь', soft_letter, word_or_sentence)
    word_or_sentence = re.sub('ъ', strong_letter, word_or_sentence)
    word_or_sentence = re.sub('ю', hiragana_letter_yu, word_or_sentence)
    print(word_or_sentence)

def rpb1e(word_or_sentence):
    word_or_sentence = re.sub('ch', letter_ch, word_or_sentence)
    word_or_sentence = re.sub('zh', letter_zh, word_or_sentence)
    word_or_sentence = re.sub('sh', letter_sh, word_or_sentence)
    word_or_sentence = re.sub('sch', letter_sch, word_or_sentence)
    word_or_sentence = re.sub('ka', hiragana_letter_ka, word_or_sentence)
    word_or_sentence = re.sub('ki', hiragana_letter_ki, word_or_sentence)
    word_or_sentence = re.sub('ku', hiragana_letter_ku, word_or_sentence)
    word_or_sentence = re.sub('ky', hiragana_letter_ku, word_or_sentence)
    word_or_sentence = re.sub('кe', hiragana_letter_ke, word_or_sentence)
    word_or_sentence = re.sub('кo', hiragana_letter_ko, word_or_sentence)
    word_or_sentence = re.sub('sa', hiragana_letter_sa, word_or_sentence)
    word_or_sentence = re.sub('si', hiragana_letter_si, word_or_sentence)
    word_or_sentence = re.sub('su', hiragana_letter_su, word_or_sentence)
    word_or_sentence = re.sub('sy', hiragana_letter_su, word_or_sentence)
    word_or_sentence = re.sub('se', hiragana_letter_se, word_or_sentence)
    word_or_sentence = re.sub('so', hiragana_letter_so, word_or_sentence)
    word_or_sentence = re.sub('na', hiragana_letter_na, word_or_sentence)
    word_or_sentence = re.sub('ni', hiragana_letter_ni, word_or_sentence)
    word_or_sentence = re.sub('nu', hiragana_letter_nu, word_or_sentence)
    word_or_sentence = re.sub('ny', hiragana_letter_nu, word_or_sentence)
    word_or_sentence = re.sub('ne', hiragana_letter_ne, word_or_sentence)
    word_or_sentence = re.sub('no', hiragana_letter_no, word_or_sentence)
    word_or_sentence = re.sub('ta', hiragana_letter_ta, word_or_sentence)
    word_or_sentence = re.sub('ti', hiragana_letter_ti, word_or_sentence)
    word_or_sentence = re.sub('tu', hiragana_letter_tu, word_or_sentence)
    word_or_sentence = re.sub('ty', hiragana_letter_tu, word_or_sentence)
    word_or_sentence = re.sub('te', hiragana_letter_te, word_or_sentence)
    word_or_sentence = re.sub('to', hiragana_letter_to, word_or_sentence)
    word_or_sentence = re.sub('ha', hiragana_letter_ha, word_or_sentence)
    word_or_sentence = re.sub('hi', hiragana_letter_hi, word_or_sentence)
    word_or_sentence = re.sub('hu', hiragana_letter_hu, word_or_sentence)
    word_or_sentence = re.sub('hy', hiragana_letter_hu, word_or_sentence)
    word_or_sentence = re.sub('he', hiragana_letter_he, word_or_sentence)
    word_or_sentence = re.sub('ho', hiragana_letter_ho, word_or_sentence)
    word_or_sentence = re.sub('ma', hiragana_letter_ma, word_or_sentence)
    word_or_sentence = re.sub('mi', hiragana_letter_mi, word_or_sentence)
    word_or_sentence = re.sub('mu', hiragana_letter_mu, word_or_sentence)
    word_or_sentence = re.sub('my', hiragana_letter_mu, word_or_sentence)
    word_or_sentence = re.sub('me', hiragana_letter_me, word_or_sentence)
    word_or_sentence = re.sub('mo', hiragana_letter_mo, word_or_sentence)
    word_or_sentence = re.sub('ya', hiragana_letter_ya, word_or_sentence)
    word_or_sentence = re.sub('yo', hiragana_letter_yo, word_or_sentence)
    word_or_sentence = re.sub('yu', hiragana_letter_yu, word_or_sentence)
    word_or_sentence = re.sub('ra', hiragana_letter_ra, word_or_sentence)
    word_or_sentence = re.sub('ri', hiragana_letter_ri, word_or_sentence)
    word_or_sentence = re.sub('tu', hiragana_letter_ru, word_or_sentence)
    word_or_sentence = re.sub('ry', hiragana_letter_ru, word_or_sentence)
    word_or_sentence = re.sub('re', hiragana_letter_re, word_or_sentence)
    word_or_sentence = re.sub('ro', hiragana_letter_ro, word_or_sentence)
    word_or_sentence = re.sub('va', hiragana_letter_wa, word_or_sentence)
    word_or_sentence = re.sub('vo', hiragana_letter_wo, word_or_sentence)
    word_or_sentence = re.sub('wa', hiragana_letter_wa, word_or_sentence)
    word_or_sentence = re.sub('wo', hiragana_letter_wo, word_or_sentence)
    word_or_sentence = re.sub('ga', hiragana_letter_ga, word_or_sentence)
    word_or_sentence = re.sub('gi', hiragana_letter_gi, word_or_sentence)
    word_or_sentence = re.sub('gu', hiragana_letter_gu, word_or_sentence)
    word_or_sentence = re.sub('gy', hiragana_letter_gu, word_or_sentence)
    word_or_sentence = re.sub('ge', hiragana_letter_ge, word_or_sentence)
    word_or_sentence = re.sub('go', hiragana_letter_go, word_or_sentence)
    word_or_sentence = re.sub('za', hiragana_letter_za, word_or_sentence)
    word_or_sentence = re.sub('zi', hiragana_letter_zi, word_or_sentence)
    word_or_sentence = re.sub('zu', hiragana_letter_zu, word_or_sentence)
    word_or_sentence = re.sub('zy', hiragana_letter_zu, word_or_sentence)
    word_or_sentence = re.sub('ze', hiragana_letter_ze, word_or_sentence)
    word_or_sentence = re.sub('zo', hiragana_letter_zo, word_or_sentence)
    word_or_sentence = re.sub('da', hiragana_letter_da, word_or_sentence)
    word_or_sentence = re.sub('di', hiragana_letter_di, word_or_sentence)
    word_or_sentence = re.sub('du', hiragana_letter_du, word_or_sentence)
    word_or_sentence = re.sub('dy', hiragana_letter_du, word_or_sentence)
    word_or_sentence = re.sub('de', hiragana_letter_de, word_or_sentence)
    word_or_sentence = re.sub('do', hiragana_letter_do, word_or_sentence)
    word_or_sentence = re.sub('pa', hiragana_letter_pa, word_or_sentence)
    word_or_sentence = re.sub('pi', hiragana_letter_pi, word_or_sentence)
    word_or_sentence = re.sub('pu', hiragana_letter_pu, word_or_sentence)
    word_or_sentence = re.sub('py', hiragana_letter_pu, word_or_sentence)
    word_or_sentence = re.sub('pe', hiragana_letter_pe, word_or_sentence)
    word_or_sentence = re.sub('po', hiragana_letter_po, word_or_sentence)
    word_or_sentence = re.sub('a', hiragana_letter_a, word_or_sentence)
    word_or_sentence = re.sub('i', hiragana_letter_i, word_or_sentence)
    word_or_sentence = re.sub('iy', hiragana_letter_i, word_or_sentence)
    word_or_sentence = re.sub('y', hiragana_letter_u, word_or_sentence)
    word_or_sentence = re.sub('u', hiragana_letter_u, word_or_sentence)
    word_or_sentence = re.sub('e', hiragana_letter_e, word_or_sentence)
    word_or_sentence = re.sub('o', hiragana_letter_o, word_or_sentence)
    word_or_sentence = re.sub('z', letter_z, word_or_sentence)
    word_or_sentence = re.sub('s', letter_s, word_or_sentence)
    word_or_sentence = re.sub('r', letter_r, word_or_sentence)
    word_or_sentence = re.sub('v', letter_v, word_or_sentence)
    word_or_sentence = re.sub('w', letter_v, word_or_sentence)
    word_or_sentence = re.sub('l', letter_l, word_or_sentence)
    word_or_sentence = re.sub('k', letter_k, word_or_sentence)
    word_or_sentence = re.sub('p', letter_p, word_or_sentence)
    word_or_sentence = re.sub('b', letter_b, word_or_sentence)
    word_or_sentence = re.sub('f', letter_f, word_or_sentence)
    word_or_sentence = re.sub('h', letter_h, word_or_sentence)
    word_or_sentence = re.sub('g', letter_g, word_or_sentence)
    word_or_sentence = re.sub('t', letter_t, word_or_sentence)
    word_or_sentence = re.sub('d', letter_d, word_or_sentence)
    word_or_sentence = re.sub('m', letter_m, word_or_sentence)
    word_or_sentence = re.sub('ts', letter_ts, word_or_sentence)
    word_or_sentence = re.sub("'", soft_letter, word_or_sentence)
    word_or_sentence = re.sub("`", strong_letter, word_or_sentence)
    print(word_or_sentence)
    with open('ids.json', mode='r') as f:
        data = json.load(f)
        id = data['id']
        id = int(id)
    with open('log.txt', mode='a') as f:
        f.write('[{}]: {}; PRINTED\n'.format(id, word_or_sentence.encode("utf-8")))
    with open('ids.json', mode='w') as f:
        id += 1
        dict = {}
        dict['id'] = id
        json.dump(dict, f)

def rpb2(word_or_sentence):
    word_or_sentence = re.sub('русский', nihongo_word_rosiajin, word_or_sentence)
    word_or_sentence = re.sub('русская', nihongo_word_rosiajin, word_or_sentence)
    word_or_sentence = re.sub('русское', nihongo_word_rosia, word_or_sentence)
    word_or_sentence = re.sub('русские', nihongo_word_rosia, word_or_sentence)
    word_or_sentence = re.sub('японец', nihongo_word_nihonjin, word_or_sentence)
    word_or_sentence = re.sub('японка', nihongo_word_nihonjin, word_or_sentence)
    word_or_sentence = re.sub('японки', nihongo_word_nihonjin, word_or_sentence)
    word_or_sentence = re.sub('японцы', nihongo_word_nihonjin, word_or_sentence)
    word_or_sentence = re.sub('японское', nihongo_word_nihon, word_or_sentence)
    word_or_sentence = re.sub('японские', nihongo_word_nihon, word_or_sentence)
    word_or_sentence = re.sub('американец', nihongo_word_amerikajin, word_or_sentence)
    word_or_sentence = re.sub('американка', nihongo_word_amerikajin, word_or_sentence)
    word_or_sentence = re.sub('американки', nihongo_word_amerikajin, word_or_sentence)
    word_or_sentence = re.sub('американцы', nihongo_word_amerikajin, word_or_sentence)
    word_or_sentence = re.sub('американское', nihongo_word_amerika, word_or_sentence)
    word_or_sentence = re.sub('американские', nihongo_word_amerika, word_or_sentence)
    word_or_sentence = re.sub('китаец', nihongo_word_chuugokujin, word_or_sentence)
    word_or_sentence = re.sub('китаянка', nihongo_word_chuugokujin, word_or_sentence)
    word_or_sentence = re.sub('китаянки', nihongo_word_chuugokujin, word_or_sentence)
    word_or_sentence = re.sub('китайцы', nihongo_word_chuugokujin, word_or_sentence)
    word_or_sentence = re.sub('китайское', nihongo_word_chuugoku, word_or_sentence)
    word_or_sentence = re.sub('китайские', nihongo_word_chuugoku, word_or_sentence)
    word_or_sentence = re.sub('англичанин', nihongo_word_igirisujin, word_or_sentence)
    word_or_sentence = re.sub('англичанка', nihongo_word_igirisujin, word_or_sentence)
    word_or_sentence = re.sub('англичане', nihongo_word_igirisujin, word_or_sentence)
    word_or_sentence = re.sub('англичанки', nihongo_word_igirisujin, word_or_sentence)
    word_or_sentence = re.sub('английское', nihongo_word_igirisu, word_or_sentence)
    word_or_sentence = re.sub('английские', nihongo_word_igirisu, word_or_sentence)
    word_or_sentence = re.sub('кореец', nihongo_word_kankokujin, word_or_sentence)
    word_or_sentence = re.sub('кореянка', nihongo_word_kankokujin, word_or_sentence)
    word_or_sentence = re.sub('корейцы', nihongo_word_kankokujin, word_or_sentence)
    word_or_sentence = re.sub('кореянки', nihongo_word_kankokujin, word_or_sentence)
    word_or_sentence = re.sub('корейское', nihongo_word_kankoku, word_or_sentence)
    word_or_sentence = re.sub('корейские', nihongo_word_kankokujin, word_or_sentence)
    word_or_sentence = re.sub('россия', nihongo_word_rosia, word_or_sentence)
    word_or_sentence = re.sub('япония', nihongo_word_nihon, word_or_sentence)
    word_or_sentence = re.sub('америка', nihongo_word_amerika, word_or_sentence)
    word_or_sentence = re.sub('китай', nihongo_word_chuugoku, word_or_sentence)
    word_or_sentence = re.sub('англия', nihongo_word_igirisu, word_or_sentence)
    word_or_sentence = re.sub('корея', nihongo_word_kankoku, word_or_sentence)
    word_or_sentence = re.sub('язык', nihongo_word_co_go, word_or_sentence)
    word_or_sentence = re.sub('ка', hiragana_letter_ka, word_or_sentence)
    word_or_sentence = re.sub('ки', hiragana_letter_ki, word_or_sentence)
    word_or_sentence = re.sub('кы', hiragana_letter_ki, word_or_sentence)
    word_or_sentence = re.sub('ку', hiragana_letter_ku, word_or_sentence)
    word_or_sentence = re.sub('кю', hiragana_letter_ku, word_or_sentence)
    word_or_sentence = re.sub('ке', hiragana_letter_ke, word_or_sentence)
    word_or_sentence = re.sub('кэ', hiragana_letter_ke, word_or_sentence)
    word_or_sentence = re.sub('ко', hiragana_letter_ko, word_or_sentence)
    word_or_sentence = re.sub('са', hiragana_letter_sa, word_or_sentence)
    word_or_sentence = re.sub('си', hiragana_letter_si, word_or_sentence)
    word_or_sentence = re.sub('сы', hiragana_letter_si, word_or_sentence)
    word_or_sentence = re.sub('су', hiragana_letter_su, word_or_sentence)
    word_or_sentence = re.sub('сю', hiragana_letter_su, word_or_sentence)
    word_or_sentence = re.sub('се', hiragana_letter_se, word_or_sentence)
    word_or_sentence = re.sub('сэ', hiragana_letter_se, word_or_sentence)
    word_or_sentence = re.sub('со', hiragana_letter_so, word_or_sentence)
    word_or_sentence = re.sub('на', hiragana_letter_na, word_or_sentence)
    word_or_sentence = re.sub('ни', hiragana_letter_ni, word_or_sentence)
    word_or_sentence = re.sub('ны', hiragana_letter_ni, word_or_sentence)
    word_or_sentence = re.sub('ну', hiragana_letter_nu, word_or_sentence)
    word_or_sentence = re.sub('ню', hiragana_letter_nu, word_or_sentence)
    word_or_sentence = re.sub('не', hiragana_letter_ne, word_or_sentence)
    word_or_sentence = re.sub('нэ', hiragana_letter_ne, word_or_sentence)
    word_or_sentence = re.sub('но', hiragana_letter_no, word_or_sentence)
    word_or_sentence = re.sub('та', hiragana_letter_ta, word_or_sentence)
    word_or_sentence = re.sub('ти', hiragana_letter_ti, word_or_sentence)
    word_or_sentence = re.sub('ты', hiragana_letter_ti, word_or_sentence)
    word_or_sentence = re.sub('ту', hiragana_letter_tu, word_or_sentence)
    word_or_sentence = re.sub('тю', hiragana_letter_tu, word_or_sentence)
    word_or_sentence = re.sub('те', hiragana_letter_te, word_or_sentence)
    word_or_sentence = re.sub('тэ', hiragana_letter_te, word_or_sentence)
    word_or_sentence = re.sub('то', hiragana_letter_to, word_or_sentence)
    word_or_sentence = re.sub('ха', hiragana_letter_ha, word_or_sentence)
    word_or_sentence = re.sub('хи', hiragana_letter_hi, word_or_sentence)
    word_or_sentence = re.sub('хы', hiragana_letter_hi, word_or_sentence)
    word_or_sentence = re.sub('ху', hiragana_letter_hu, word_or_sentence)
    word_or_sentence = re.sub('хю', hiragana_letter_hu, word_or_sentence)
    word_or_sentence = re.sub('хе', hiragana_letter_he, word_or_sentence)
    word_or_sentence = re.sub('хэ', hiragana_letter_he, word_or_sentence)
    word_or_sentence = re.sub('хо', hiragana_letter_ho, word_or_sentence)
    word_or_sentence = re.sub('ма', hiragana_letter_ma, word_or_sentence)
    word_or_sentence = re.sub('ми', hiragana_letter_mi, word_or_sentence)
    word_or_sentence = re.sub('мы', hiragana_letter_mi, word_or_sentence)
    word_or_sentence = re.sub('му', hiragana_letter_mu, word_or_sentence)
    word_or_sentence = re.sub('мю', hiragana_letter_mu, word_or_sentence)
    word_or_sentence = re.sub('ме', hiragana_letter_me, word_or_sentence)
    word_or_sentence = re.sub('мэ', hiragana_letter_me, word_or_sentence)
    word_or_sentence = re.sub('мо', hiragana_letter_mo, word_or_sentence)
    word_or_sentence = re.sub('я', hiragana_letter_ya, word_or_sentence)
    word_or_sentence = re.sub('ё', hiragana_letter_yo, word_or_sentence)
    word_or_sentence = re.sub('ра', hiragana_letter_ra, word_or_sentence)
    word_or_sentence = re.sub('ри', hiragana_letter_ri, word_or_sentence)
    word_or_sentence = re.sub('ры', hiragana_letter_ri, word_or_sentence)
    word_or_sentence = re.sub('ру', hiragana_letter_ru, word_or_sentence)
    word_or_sentence = re.sub('рю', hiragana_letter_ru, word_or_sentence)
    word_or_sentence = re.sub('ре', hiragana_letter_re, word_or_sentence)
    word_or_sentence = re.sub('рэ', hiragana_letter_re, word_or_sentence)
    word_or_sentence = re.sub('ро', hiragana_letter_ro, word_or_sentence)
    word_or_sentence = re.sub('ва', hiragana_letter_wa, word_or_sentence)
    word_or_sentence = re.sub('во', hiragana_letter_wo, word_or_sentence)
    word_or_sentence = re.sub('н', hiragana_letter_n, word_or_sentence)
    word_or_sentence = re.sub('га', hiragana_letter_ga, word_or_sentence)
    word_or_sentence = re.sub('ги', hiragana_letter_gi, word_or_sentence)
    word_or_sentence = re.sub('гы', hiragana_letter_gi, word_or_sentence)
    word_or_sentence = re.sub('гу', hiragana_letter_gu, word_or_sentence)
    word_or_sentence = re.sub('гю', hiragana_letter_gu, word_or_sentence)
    word_or_sentence = re.sub('ге', hiragana_letter_ge, word_or_sentence)
    word_or_sentence = re.sub('гэ', hiragana_letter_ge, word_or_sentence)
    word_or_sentence = re.sub('го', hiragana_letter_go, word_or_sentence)
    word_or_sentence = re.sub('за', hiragana_letter_za, word_or_sentence)
    word_or_sentence = re.sub('зи', hiragana_letter_zi, word_or_sentence)
    word_or_sentence = re.sub('зы', hiragana_letter_zi, word_or_sentence)
    word_or_sentence = re.sub('зу', hiragana_letter_zu, word_or_sentence)
    word_or_sentence = re.sub('зю', hiragana_letter_zu, word_or_sentence)
    word_or_sentence = re.sub('зе', hiragana_letter_ze, word_or_sentence)
    word_or_sentence = re.sub('зэ', hiragana_letter_ze, word_or_sentence)
    word_or_sentence = re.sub('зо', hiragana_letter_zo, word_or_sentence)
    word_or_sentence = re.sub('да', hiragana_letter_da, word_or_sentence)
    word_or_sentence = re.sub('ди', hiragana_letter_di, word_or_sentence)
    word_or_sentence = re.sub('ды', hiragana_letter_di, word_or_sentence)
    word_or_sentence = re.sub('ду', hiragana_letter_du, word_or_sentence)
    word_or_sentence = re.sub('дю', hiragana_letter_du, word_or_sentence)
    word_or_sentence = re.sub('де', hiragana_letter_de, word_or_sentence)
    word_or_sentence = re.sub('дэ', hiragana_letter_de, word_or_sentence)
    word_or_sentence = re.sub('до', hiragana_letter_do, word_or_sentence)
    word_or_sentence = re.sub('па', hiragana_letter_pa, word_or_sentence)
    word_or_sentence = re.sub('пи', hiragana_letter_pi, word_or_sentence)
    word_or_sentence = re.sub('пы', hiragana_letter_pi, word_or_sentence)
    word_or_sentence = re.sub('пу', hiragana_letter_pu, word_or_sentence)
    word_or_sentence = re.sub('пю', hiragana_letter_pu, word_or_sentence)
    word_or_sentence = re.sub('пе', hiragana_letter_pe, word_or_sentence)
    word_or_sentence = re.sub('пэ', hiragana_letter_pe, word_or_sentence)
    word_or_sentence = re.sub('по', hiragana_letter_po, word_or_sentence)
    word_or_sentence = re.sub('ба', hiragana_letter_ba, word_or_sentence)
    word_or_sentence = re.sub('би', hiragana_letter_bi, word_or_sentence)
    word_or_sentence = re.sub('бы', hiragana_letter_bi, word_or_sentence)
    word_or_sentence = re.sub('бу', hiragana_letter_bu, word_or_sentence)
    word_or_sentence = re.sub('бю', hiragana_letter_bu, word_or_sentence)
    word_or_sentence = re.sub('бе', hiragana_letter_be, word_or_sentence)
    word_or_sentence = re.sub('бэ', hiragana_letter_be, word_or_sentence)
    word_or_sentence = re.sub('бо', hiragana_letter_bo, word_or_sentence)
    word_or_sentence = re.sub('а', hiragana_letter_a, word_or_sentence)
    word_or_sentence = re.sub('и', hiragana_letter_i, word_or_sentence)
    word_or_sentence = re.sub('й', hiragana_letter_i, word_or_sentence)
    word_or_sentence = re.sub('у', hiragana_letter_u, word_or_sentence)
    word_or_sentence = re.sub('е', hiragana_letter_e, word_or_sentence)
    word_or_sentence = re.sub('э', hiragana_letter_e, word_or_sentence)
    word_or_sentence = re.sub('о', hiragana_letter_o, word_or_sentence)
    word_or_sentence = re.sub('з', letter_z, word_or_sentence)
    word_or_sentence = re.sub('с', letter_s, word_or_sentence)
    word_or_sentence = re.sub('р', letter_r, word_or_sentence)
    word_or_sentence = re.sub('в', letter_v, word_or_sentence)
    word_or_sentence = re.sub('л', letter_l, word_or_sentence)
    word_or_sentence = re.sub('к', letter_k, word_or_sentence)
    word_or_sentence = re.sub('п', letter_p, word_or_sentence)
    word_or_sentence = re.sub('б', letter_b, word_or_sentence)
    word_or_sentence = re.sub('ф', letter_f, word_or_sentence)
    word_or_sentence = re.sub('х', letter_h, word_or_sentence)
    word_or_sentence = re.sub('г', letter_g, word_or_sentence)
    word_or_sentence = re.sub('т', letter_t, word_or_sentence)
    word_or_sentence = re.sub('д', letter_d, word_or_sentence)
    word_or_sentence = re.sub('м', letter_m, word_or_sentence)
    word_or_sentence = re.sub('ц', letter_ts, word_or_sentence)
    word_or_sentence = re.sub('ч', letter_ch, word_or_sentence)
    word_or_sentence = re.sub('ж', letter_zh, word_or_sentence)
    word_or_sentence = re.sub('ш', letter_sh, word_or_sentence)
    word_or_sentence = re.sub('щ', letter_sch, word_or_sentence)
    word_or_sentence = re.sub('ь', soft_letter, word_or_sentence)
    word_or_sentence = re.sub('ъ', strong_letter, word_or_sentence)
    word_or_sentence = re.sub('ю', hiragana_letter_yu, word_or_sentence)
    print(word_or_sentence)
    with open('ids.json', mode='r') as f:
        data = json.load(f)
        id = data['id']
        id = int(id)
    with open('log.txt', mode='a') as f:
        f.write('[{}]: {}; PRINTED\n'.format(id, word_or_sentence.encode("utf-8")))
    with open('ids.json', mode='w') as f:
        id += 1
        dict = {}
        dict['id'] = id
        json.dump(dict, f)

def rpb2e(word_or_sentence):
    word_or_sentence = re.sub('russian', nihongo_word_rosiajin, word_or_sentence)
    word_or_sentence = re.sub('russians', nihongo_word_rosiajin, word_or_sentence)
    word_or_sentence = re.sub('japanese', nihongo_word_nihonjin, word_or_sentence)
    word_or_sentence = re.sub('japaneses', nihongo_word_nihonjin, word_or_sentence)
    word_or_sentence = re.sub('amerikan', nihongo_word_amerikajin, word_or_sentence)
    word_or_sentence = re.sub('amerikans', nihongo_word_amerikajin, word_or_sentence)
    word_or_sentence = re.sub('chinese', nihongo_word_chuugokujin, word_or_sentence)
    word_or_sentence = re.sub('chineses', nihongo_word_chuugokujin, word_or_sentence)
    word_or_sentence = re.sub('englishman', nihongo_word_igirisujin, word_or_sentence)
    word_or_sentence = re.sub('englishmans', nihongo_word_igirisujin, word_or_sentence)
    word_or_sentence = re.sub('korean', nihongo_word_kankokujin, word_or_sentence)
    word_or_sentence = re.sub('koreans', nihongo_word_kankokujin, word_or_sentence)
    word_or_sentence = re.sub('russia', nihongo_word_rosia, word_or_sentence)
    word_or_sentence = re.sub('japan', nihongo_word_nihon, word_or_sentence)
    word_or_sentence = re.sub('amerika', nihongo_word_amerika, word_or_sentence)
    word_or_sentence = re.sub('china', nihongo_word_chuugoku, word_or_sentence)
    word_or_sentence = re.sub('england', nihongo_word_igirisu, word_or_sentence)
    word_or_sentence = re.sub('korea', nihongo_word_kankoku, word_or_sentence)
    word_or_sentence = re.sub('language', nihongo_word_co_go, word_or_sentence)
    word_or_sentence = re.sub('ch', letter_ch, word_or_sentence)
    word_or_sentence = re.sub('zh', letter_zh, word_or_sentence)
    word_or_sentence = re.sub('sh', letter_sh, word_or_sentence)
    word_or_sentence = re.sub('sch', letter_sch, word_or_sentence)
    word_or_sentence = re.sub('ka', hiragana_letter_ka, word_or_sentence)
    word_or_sentence = re.sub('ki', hiragana_letter_ki, word_or_sentence)
    word_or_sentence = re.sub('ku', hiragana_letter_ku, word_or_sentence)
    word_or_sentence = re.sub('ky', hiragana_letter_ku, word_or_sentence)
    word_or_sentence = re.sub('кe', hiragana_letter_ke, word_or_sentence)
    word_or_sentence = re.sub('кo', hiragana_letter_ko, word_or_sentence)
    word_or_sentence = re.sub('sa', hiragana_letter_sa, word_or_sentence)
    word_or_sentence = re.sub('si', hiragana_letter_si, word_or_sentence)
    word_or_sentence = re.sub('su', hiragana_letter_su, word_or_sentence)
    word_or_sentence = re.sub('sy', hiragana_letter_su, word_or_sentence)
    word_or_sentence = re.sub('se', hiragana_letter_se, word_or_sentence)
    word_or_sentence = re.sub('so', hiragana_letter_so, word_or_sentence)
    word_or_sentence = re.sub('na', hiragana_letter_na, word_or_sentence)
    word_or_sentence = re.sub('ni', hiragana_letter_ni, word_or_sentence)
    word_or_sentence = re.sub('nu', hiragana_letter_nu, word_or_sentence)
    word_or_sentence = re.sub('ny', hiragana_letter_nu, word_or_sentence)
    word_or_sentence = re.sub('ne', hiragana_letter_ne, word_or_sentence)
    word_or_sentence = re.sub('no', hiragana_letter_no, word_or_sentence)
    word_or_sentence = re.sub('ta', hiragana_letter_ta, word_or_sentence)
    word_or_sentence = re.sub('ti', hiragana_letter_ti, word_or_sentence)
    word_or_sentence = re.sub('tu', hiragana_letter_tu, word_or_sentence)
    word_or_sentence = re.sub('ty', hiragana_letter_tu, word_or_sentence)
    word_or_sentence = re.sub('te', hiragana_letter_te, word_or_sentence)
    word_or_sentence = re.sub('to', hiragana_letter_to, word_or_sentence)
    word_or_sentence = re.sub('ha', hiragana_letter_ha, word_or_sentence)
    word_or_sentence = re.sub('hi', hiragana_letter_hi, word_or_sentence)
    word_or_sentence = re.sub('hu', hiragana_letter_hu, word_or_sentence)
    word_or_sentence = re.sub('hy', hiragana_letter_hu, word_or_sentence)
    word_or_sentence = re.sub('he', hiragana_letter_he, word_or_sentence)
    word_or_sentence = re.sub('ho', hiragana_letter_ho, word_or_sentence)
    word_or_sentence = re.sub('ma', hiragana_letter_ma, word_or_sentence)
    word_or_sentence = re.sub('mi', hiragana_letter_mi, word_or_sentence)
    word_or_sentence = re.sub('mu', hiragana_letter_mu, word_or_sentence)
    word_or_sentence = re.sub('my', hiragana_letter_mu, word_or_sentence)
    word_or_sentence = re.sub('me', hiragana_letter_me, word_or_sentence)
    word_or_sentence = re.sub('mo', hiragana_letter_mo, word_or_sentence)
    word_or_sentence = re.sub('ya', hiragana_letter_ya, word_or_sentence)
    word_or_sentence = re.sub('yo', hiragana_letter_yo, word_or_sentence)
    word_or_sentence = re.sub('yu', hiragana_letter_yu, word_or_sentence)
    word_or_sentence = re.sub('ra', hiragana_letter_ra, word_or_sentence)
    word_or_sentence = re.sub('ri', hiragana_letter_ri, word_or_sentence)
    word_or_sentence = re.sub('tu', hiragana_letter_ru, word_or_sentence)
    word_or_sentence = re.sub('ry', hiragana_letter_ru, word_or_sentence)
    word_or_sentence = re.sub('re', hiragana_letter_re, word_or_sentence)
    word_or_sentence = re.sub('ro', hiragana_letter_ro, word_or_sentence)
    word_or_sentence = re.sub('va', hiragana_letter_wa, word_or_sentence)
    word_or_sentence = re.sub('vo', hiragana_letter_wo, word_or_sentence)
    word_or_sentence = re.sub('wa', hiragana_letter_wa, word_or_sentence)
    word_or_sentence = re.sub('wo', hiragana_letter_wo, word_or_sentence)
    word_or_sentence = re.sub('ga', hiragana_letter_ga, word_or_sentence)
    word_or_sentence = re.sub('gi', hiragana_letter_gi, word_or_sentence)
    word_or_sentence = re.sub('gu', hiragana_letter_gu, word_or_sentence)
    word_or_sentence = re.sub('gy', hiragana_letter_gu, word_or_sentence)
    word_or_sentence = re.sub('ge', hiragana_letter_ge, word_or_sentence)
    word_or_sentence = re.sub('go', hiragana_letter_go, word_or_sentence)
    word_or_sentence = re.sub('za', hiragana_letter_za, word_or_sentence)
    word_or_sentence = re.sub('zi', hiragana_letter_zi, word_or_sentence)
    word_or_sentence = re.sub('zu', hiragana_letter_zu, word_or_sentence)
    word_or_sentence = re.sub('zy', hiragana_letter_zu, word_or_sentence)
    word_or_sentence = re.sub('ze', hiragana_letter_ze, word_or_sentence)
    word_or_sentence = re.sub('zo', hiragana_letter_zo, word_or_sentence)
    word_or_sentence = re.sub('da', hiragana_letter_da, word_or_sentence)
    word_or_sentence = re.sub('di', hiragana_letter_di, word_or_sentence)
    word_or_sentence = re.sub('du', hiragana_letter_du, word_or_sentence)
    word_or_sentence = re.sub('dy', hiragana_letter_du, word_or_sentence)
    word_or_sentence = re.sub('de', hiragana_letter_de, word_or_sentence)
    word_or_sentence = re.sub('do', hiragana_letter_do, word_or_sentence)
    word_or_sentence = re.sub('pa', hiragana_letter_pa, word_or_sentence)
    word_or_sentence = re.sub('pi', hiragana_letter_pi, word_or_sentence)
    word_or_sentence = re.sub('pu', hiragana_letter_pu, word_or_sentence)
    word_or_sentence = re.sub('py', hiragana_letter_pu, word_or_sentence)
    word_or_sentence = re.sub('pe', hiragana_letter_pe, word_or_sentence)
    word_or_sentence = re.sub('po', hiragana_letter_po, word_or_sentence)
    word_or_sentence = re.sub('a', hiragana_letter_a, word_or_sentence)
    word_or_sentence = re.sub('i', hiragana_letter_i, word_or_sentence)
    word_or_sentence = re.sub('iy', hiragana_letter_i, word_or_sentence)
    word_or_sentence = re.sub('y', hiragana_letter_u, word_or_sentence)
    word_or_sentence = re.sub('u', hiragana_letter_u, word_or_sentence)
    word_or_sentence = re.sub('e', hiragana_letter_e, word_or_sentence)
    word_or_sentence = re.sub('o', hiragana_letter_o, word_or_sentence)
    word_or_sentence = re.sub('z', letter_z, word_or_sentence)
    word_or_sentence = re.sub('s', letter_s, word_or_sentence)
    word_or_sentence = re.sub('r', letter_r, word_or_sentence)
    word_or_sentence = re.sub('v', letter_v, word_or_sentence)
    word_or_sentence = re.sub('w', letter_v, word_or_sentence)
    word_or_sentence = re.sub('l', letter_l, word_or_sentence)
    word_or_sentence = re.sub('k', letter_k, word_or_sentence)
    word_or_sentence = re.sub('p', letter_p, word_or_sentence)
    word_or_sentence = re.sub('b', letter_b, word_or_sentence)
    word_or_sentence = re.sub('f', letter_f, word_or_sentence)
    word_or_sentence = re.sub('h', letter_h, word_or_sentence)
    word_or_sentence = re.sub('g', letter_g, word_or_sentence)
    word_or_sentence = re.sub('t', letter_t, word_or_sentence)
    word_or_sentence = re.sub('d', letter_d, word_or_sentence)
    word_or_sentence = re.sub('m', letter_m, word_or_sentence)
    word_or_sentence = re.sub('ts', letter_ts, word_or_sentence)
    word_or_sentence = re.sub("'", soft_letter, word_or_sentence)
    word_or_sentence = re.sub("`", strong_letter, word_or_sentence)
    print(word_or_sentence)
    with open('ids.json', mode='r') as f:
        data = json.load(f)
        id = data['id']
        id = int(id)
    with open('log.txt', mode='a') as f:
        f.write('[{}]: {}; PRINTED\n'.format(id, word_or_sentence.encode("utf-8")))
    with open('ids.json', mode='w') as f:
        id += 1
        dict = {}
        dict['id'] = id
        json.dump(dict, f)